### ISSUE TITLE
Alteração do Footer do Tema

### ISSUE THREAD

**Issue by jppcel** [mozillabrasil/frontierline-theme#5]
Alterar o footer para ficar dentro do padrão selecionado:
![page-shot-2017-4-30 1b0873ee-feb1-11e6-99a9-c5b57d97d544 png imagem png 1440 x 1790 pixels 2](https://cloud.githubusercontent.com/assets/3324772/25569892/006dbd0a-2df5-11e7-9430-e6f010dfdc68.png)

**Comment by felipez3r0** [comment]
Alteração realizada em #9
